version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - snyk/scan
workflows:
  build_test_deploy:
    jobs:
      - build_test
