name: Docker Image - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ddso/scanner:latest 

  login:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1 
        with:
          username: ddso
          password: a7990fdb-7a9f-440c-8fa7-64f9e87b5a69
      
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ddso/scanner:latest     

  scan:
    name:  Vulnerability Scan
    needs: login
    uses: azure/container-scan@v0
    with:
      image-name: ddso/scanner:latest
