name: Docker Image - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ddso/scanner:latest 

  login:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1 
        with:
          username: ddso
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ddso/scanner:latest     


